Fix up web.xml config
Add missing WebServlet annotation to JavascriptConfigServlet class, for
consistency.
Remove redundant configuration items from web.xml, as on Tomcat 7 with
default settings these cause the following error:
java.lang.IllegalArgumentException: The servlets named
[JavascriptConfigServlet] and
[net.socialgamer.cah.servlets.JavascriptConfigServlet] are both mapped
to the url-pattern [/js/cah.config.js] which is not permitted